const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE}:{}),args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.BASE_URL||'http://localhost:5173');
 await page.getByLabel('Votre prénom').fill('Rayan');
 await page.getByLabel('Adresse email').fill('rayan-'+Date.now()+'@example.com');
 await page.getByLabel('Mot de passe',{exact:true}).fill('test-local-Strong-2026');
 await page.getByRole('button',{name:'Activer mon radar'}).click();
 await page.getByRole('heading',{name:'Le bon signal.'}).waitFor();
 await page.getByRole('link',{name:'Configurer mon profil'}).click();
 await page.getByLabel('Compétences · séparées').fill('Python, SQL, Docker, React');
 await page.getByLabel('Ville',{exact:true}).fill('Marseille');
 await page.getByRole('button',{name:'Data',exact:true}).click();
 await page.getByRole('button',{name:'IA',exact:true}).click();
 await page.getByRole('button',{name:'CDI',exact:true}).click();
 await page.getByRole('button',{name:'Enregistrer mon profil'}).click();
 await page.getByText('Profil enregistré. Votre radar est à jour.').waitFor();
 await page.getByRole('link',{name:'Studio CV',exact:true}).click();
 await page.getByRole('button',{name:'Coller le texte'}).click();
 await page.getByLabel('Nom du document').fill('CV Rayan');
 await page.getByLabel('Votre parcours').fill('Rayan — Ingénieur informatique\nProjet Python et SQL : automatisation des rapports.\nDéveloppement React pour un outil scolaire.\nUtilisation Docker sur Linux.\nLicence informatique obtenue en 2024.');
 await page.getByRole('button',{name:'Enregistrer le CV'}).click();
 await page.getByRole('heading',{name:'CV Rayan',exact:true}).waitFor();
 await page.getByRole('link',{name:'Mon radar',exact:true}).click();
 await page.locator('.job-card').first().waitFor();
 await page.screenshot({path:require('path').resolve(__dirname,'../../docs/radar-desktop.png'),fullPage:false});
 await page.locator('.job-card').first().getByRole('button',{name:'Explorer'}).click();
 await page.getByRole('button',{name:'Adapter mon CV',exact:true}).click();
 await page.getByText('Version créée').waitFor();
 const downloadPromise=page.waitForEvent('download');await page.getByRole('link',{name:'Télécharger DOCX'}).click();const download=await downloadPromise;
 if(!download.suggestedFilename().endsWith('.docx'))throw new Error('Bad DOCX export');
 await page.getByRole('dialog').getByRole('button',{name:'Enregistrer',exact:true}).click();await page.getByRole('button',{name:'Enregistrée',exact:true}).waitFor();
 await page.getByRole('button',{name:'Fermer',exact:true}).click();
 await page.getByRole('link',{name:'Mes candidatures',exact:true}).click();
 await page.locator('.saved-row select').first().selectOption('interview');
 await page.waitForTimeout(300);
 await page.getByRole('link',{name:'Mon radar',exact:true}).click();
 await page.getByRole('textbox',{name:'Rechercher un métier'}).fill('Python');
 await page.waitForTimeout(500);if(await page.locator('.job-card').count()===0)throw new Error('Search failed');
 await page.getByRole('textbox',{name:'Rechercher un métier'}).fill('');await page.waitForTimeout(500);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(400);await page.locator('h1').click();
 await page.screenshot({path:require('path').resolve(__dirname,'../../docs/radar-mobile.png'),fullPage:false});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 if(overflow)throw new Error('Mobile horizontal overflow');
 await page.getByRole('button',{name:'Ouvrir le menu'}).click();await page.getByRole('link',{name:'Entreprises',exact:true}).click();await page.locator('.company-card').first().waitFor();
 await page.getByRole('button',{name:'Ouvrir le menu'}).click();await page.getByRole('button',{name:'Se déconnecter'}).click();await page.getByRole('button',{name:'Activer mon radar'}).waitFor();
 if(errors.length)throw new Error(errors.join('; '));console.log('PASS: register, profile, resume, matching, tailoring, DOCX download, saved stages, search, mobile navigation, logout; no JS errors or overflow.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
