import {useEffect,useState} from 'react';
import {Plus,Search,ArrowUpRight,RefreshCw,Pause,Play,ChevronLeft,ChevronRight} from 'lucide-react';
import {api,json} from './api';
import {Tag,Empty,Loading,Modal,dateLabel} from './components';
import type {Company,User} from './types';
export default function Companies({user,adminView=false}:{user:User;adminView?:boolean}){
 const [companies,setCompanies]=useState<Company[]>([]),[total,setTotal]=useState(0),[page,setPage]=useState(1),[search,setSearch]=useState(''),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState(''),[runs,setRuns]=useState<any[]>([]),[connectors,setConnectors]=useState<any[]>([]),[add,setAdd]=useState(false),[busy,setBusy]=useState(false),[form,setForm]=useState({name:'',website_url:'',career_url:'',ats_provider:'generic',ats_id:'',industry:'Tech',country:'France'});
 async function load(){try{const data=await api('/companies?'+new URLSearchParams({q,page:String(page),limit:'18'}));setCompanies(data.items);setTotal(data.total);if(user.is_admin&&adminView)setRuns(await api('/admin/crawls'))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(()=>{setQ(search);setPage(1)},300);return()=>clearTimeout(t)},[search]);
 useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[q,page,adminView]);
 useEffect(()=>{api<any[]>('/connectors').then(setConnectors).catch(e=>setError(e.message))},[]);
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/admin/companies',{method:'POST',body:json({...form,career_url:form.career_url||null,ats_id:form.ats_id||null})});setAdd(false);setForm({name:'',website_url:'',career_url:'',ats_provider:'generic',ats_id:'',industry:'Tech',country:'France'});setSuccess('Entreprise ajoutée. Lancez une collecte pour découvrir ses offres.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function crawl(c:Company){setBusy(true);setError('');try{await api('/admin/companies/'+c.id+'/crawl',{method:'POST'});setSuccess('Collecte mise en file pour '+c.name+'. Les statuts sont actualisés toutes les 15 secondes.');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function toggle(c:Company){try{await api('/admin/companies/'+c.id+'/enabled?enabled='+!c.enabled,{method:'PATCH'});await load()}catch(e:any){setError(e.message)}}
 return <><div className="simple-heading heading-actions"><div><div className="eyebrow">{adminView?'CONTROL ROOM':'LE RÉSEAU À LA SOURCE'}</div><h1>{adminView?'Le moteur de découverte.':'Explorez les entreprises.'}</h1><p>{adminView?'Supervisez les collectes, les connecteurs et leur couverture.':'Les pages carrière derrière votre prochain signal.'}</p></div>{user.is_admin&&<button className="btn primary" onClick={()=>setAdd(true)}><Plus size={17}/>Ajouter une entreprise</button>}</div>{error&&<p className="error" role="alert">{error}</p>}{success&&<p className="success" role="status">{success}</p>}
 {adminView&&<div className="connector-grid">{connectors.map(c=><div className="connector" key={c.name}><span className={'status-dot '+(c.closure_supported?'green':'amber')}/><div><strong>{c.name}</strong><small>{c.mode}</small></div></div>)}</div>}
 <div className="filter-bar"><label className="search-field"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher une entreprise…" aria-label="Rechercher une entreprise"/></label><Tag>{total} entreprises</Tag><button className="icon-btn" onClick={load} aria-label="Actualiser"><RefreshCw size={18}/></button></div>
 {loading?<Loading/>:companies.length?<div className="company-grid">{companies.map(c=><article className="panel company-card" key={c.id}><div className="card-top"><span className={'company-avatar avatar-'+c.name.charCodeAt(0)%4}>{c.name.slice(0,2).toUpperCase()}</span><div className="company-meta"><h3>{c.name}</h3><small>{c.industry} · {c.country||'International'}</small></div>{c.is_demo&&<Tag tone="amber">Démo</Tag>}</div><div className="company-numbers"><strong>{c.active_jobs}</strong><span>offres actives</span><Tag>{c.is_demo?'Fictif':c.ats_provider}</Tag></div><div className="crawl-status"><span className={'status-dot '+(['success','partial'].includes(c.crawler_status)?'green':'')}/>{c.is_demo?'Collecte désactivée':c.crawler_status}<span>Dernier crawl : {dateLabel(c.last_crawl)}</span></div><div className="company-actions">{!c.is_demo&&<a className="text-btn" href={c.career_url||c.website_url} target="_blank" rel="noopener noreferrer">Site carrière <ArrowUpRight size={16}/></a>}{user.is_admin&&!c.is_demo&&<><button className="btn small" disabled={busy||['queued','running','retry'].includes(c.crawler_status)} onClick={()=>crawl(c)}><RefreshCw size={14}/>Collecter</button><button className="icon-btn" aria-label={c.enabled?'Suspendre les collectes planifiées':'Activer les collectes planifiées'} onClick={()=>toggle(c)}>{c.enabled?<Pause size={16}/>:<Play size={16}/>}</button></>}</div></article>)}</div>:<Empty title="Aucune entreprise trouvée">Ajoutez une entreprise avec son domaine et, si vous le connaissez, son identifiant ATS.</Empty>}
 {total>18&&<div className="pagination"><button className="btn" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/>Précédent</button><span>{page} / {Math.ceil(total/18)}</span><button className="btn" disabled={page*18>=total} onClick={()=>setPage(page+1)}>Suivant<ChevronRight size={16}/></button></div>}
 {adminView&&<><div className="section-heading"><h2>Journal des collectes</h2><span className="fine">100 dernières exécutions</span></div><div className="table-wrap"><table><thead><tr><th>Entreprise</th><th>État</th><th>Offres</th><th>Couverture</th><th>Essais</th><th>Détail</th></tr></thead><tbody>{runs.map(r=><tr key={r.id}><td>{r.company}<small>{dateLabel(r.started_at)}</small></td><td><Tag tone={r.status==='success'?'lime':r.status==='error'?'amber':''}>{r.status}</Tag></td><td>{r.count}</td><td>{r.complete?'Complète':'Partielle / en attente'}</td><td>{r.attempts}</td><td>{r.error||'—'}</td></tr>)}</tbody></table>{!runs.length&&<Empty title="Aucune collecte exécutée">Ajoutez une entreprise réelle et lancez sa première analyse.</Empty>}</div><p className="fine">Respect de robots.txt, requêtes conditionnelles et limitation par domaine. Workday, Teamtailor, SuccessFactors et Taleo : extraction JSON-LD uniquement, sans connecteur API dédié ni fermeture automatique.</p></>}
 {add&&<Modal title="Ajouter une source entreprise" onClose={()=>setAdd(false)}><form onSubmit={create}><div className="form-grid"><label>Nom<input required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Secteur<input required value={form.industry} onChange={e=>setForm({...form,industry:e.target.value})}/></label></div><label>Site officiel<input required type="url" value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})} placeholder="https://entreprise.fr"/></label><label>Page carrière (facultatif)<input type="url" value={form.career_url} onChange={e=>setForm({...form,career_url:e.target.value})} placeholder="https://entreprise.fr/careers"/></label><div className="form-grid"><label>Connecteur<select value={form.ats_provider} onChange={e=>setForm({...form,ats_provider:e.target.value})}>{connectors.map(c=><option key={c.name} value={c.name}>{c.name} · {c.mode}</option>)}</select></label><label>Identifiant ATS<input value={form.ats_id} pattern="[a-zA-Z0-9_-]{1,150}" onChange={e=>setForm({...form,ats_id:e.target.value})} placeholder="Nom du job board"/></label></div><p className="notice">Sans URL carrière, le mode générique examine le site, son sitemap et les chemins usuels. Pour une API ATS, indiquez son identifiant public exact.</p>{error&&<p className="error">{error}</p>}<button className="btn primary" disabled={busy}>{busy?'Ajout…':'Ajouter au réseau'}</button></form></Modal>}</>
}
