import {useEffect,useRef, type ReactNode} from 'react';
import {X,ArrowUpRight,MapPin,Bookmark,Check,Radio} from 'lucide-react';
import type {Job} from './types';
export const remoteLabels:Record<string,string>={remote:'Télétravail',hybrid:'Hybride',onsite:'Sur site',unknown:'Non précisé'};
export const stageLabels:Record<string,string>={saved:'À explorer',applied:'Candidature envoyée',interview:'Entretien',offer:'Proposition',rejected:'Sans suite'};
export const dateLabel=(value:string|null)=>value?new Date(value.endsWith('Z')?value:value+'Z').toLocaleDateString('fr-FR',{day:'numeric',month:'short'}):'Jamais';
export function Logo(){return <div className="brand"><img src="/favicon.svg" alt=""/><span>SIGNAL<span className="brand-dot">.</span></span></div>}
export function Tag({children,tone=''}:{children:ReactNode;tone?:string}){return <span className={'tag '+tone}>{children}</span>}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><Radio size={34}/><h3>{title}</h3><p>{children}</p></div>}
export function Loading(){return <div className="loading" role="status"><span className="spinner"/>Recherche du signal…</div>}
export function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement;const bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();
  function key(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus()}}}
  document.addEventListener('keydown',key);return()=>{document.body.style.overflow=bodyOverflow;document.removeEventListener('keydown',key);previous?.focus()};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} className={'modal '+(wide?'wide':'')}><div className="modal-heading"><h2>{title}</h2><button className="icon-btn" aria-label="Fermer" onClick={onClose}><X/></button></div>{children}</div></div>
}
export function JobCard({job,onOpen,onSave}:{job:Job;onOpen:()=>void;onSave:()=>void}){
 return <article className="job-card"><div className="card-top"><span className={'company-avatar avatar-'+job.company.charCodeAt(0)%4}>{job.company.slice(0,2).toUpperCase()}</span><div className="company-meta"><span>{job.company}</span><small>{job.domain}</small></div><button className={'icon-btn save '+(job.saved_stage?'is-saved':'')} title={job.saved_stage?'Retirer des favoris':'Enregistrer'} aria-label={job.saved_stage?'Retirer des favoris':'Enregistrer'} onClick={onSave}>{job.saved_stage?<Check size={19}/>:<Bookmark size={19}/>}</button></div><button className="job-title" onClick={onOpen}>{job.title}</button><div className="job-location"><MapPin size={14}/>{job.city||job.location||'Lieu non précisé'}<span>·</span>{remoteLabels[job.remote_type]||job.remote_type}</div><div className="tags"><Tag>{job.contract_type==='unknown'?'Contrat non précisé':job.contract_type}</Tag>{job.skills.slice(0,3).map(s=><Tag key={s} tone="muted">{s}</Tag>)}</div><p className="job-summary">{job.short_description}</p><div className="card-footer"><span className={'score '+(job.match.score!==null&&job.match.score>=65?'good':'')}>{job.match.score!==null?<><span className="score-dot"/>{job.match.score}% compatible</>:'Compléter mon profil'}</span><button className="text-btn" onClick={onOpen}>Explorer <ArrowUpRight size={16}/></button></div><div className="source-line"><span>{job.is_demo?'DONNÉE FICTIVE · DÉMO':'SOURCE DIRECTE · '+job.source.toUpperCase()}</span><span>{dateLabel(job.first_seen)}</span></div></article>
}
