import {useEffect,useState} from 'react';
import {Search,SlidersHorizontal,ArrowUpRight,ArrowRight,Radio,Globe,Bookmark,ChevronLeft,ChevronRight,Check,FileText} from 'lucide-react';
import {api,json} from './api';
import {Tag,Empty,Loading,Modal,JobCard,remoteLabels,dateLabel} from './components';
import type {Job,Resume,User} from './types';
export function JobDetail({id,onClose,onSaved,onTailored,user}:{id:string;onClose:()=>void;onSaved:()=>void;onTailored:()=>void;user:User}){
 const [job,setJob]=useState<any>(null),[error,setError]=useState(''),[resumes,setResumes]=useState<Resume[]>([]),[resume,setResume]=useState(''),[busy,setBusy]=useState(false),[useAI,setAI]=useState(false),[result,setResult]=useState<any>(null),[saved,setSaved]=useState(false);
 useEffect(()=>{Promise.all([api('/jobs/'+id),api<Resume[]>('/resumes')]).then(([j,r])=>{setJob(j);setResumes(r);setResume(r[0]?.id||'')}).catch(e=>setError(e.message))},[id]);
 async function save(){setBusy(true);try{await api('/saved/'+id,{method:'PUT',body:json({stage:'saved'})});setSaved(true);onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function tailor(){setBusy(true);setError('');try{setResult(await api('/resumes/tailor',{method:'POST',body:json({resume_id:resume,job_id:id,use_ai:useAI})}));onTailored()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <Modal wide title="Signal détecté" onClose={onClose}>{error&&<p role="alert" className="error">{error}</p>}{!job?<Loading/>:<><div className="detail-intro"><div><div className="eyebrow">{job.company.name} / {job.domain}</div><h1>{job.title}</h1><p>{job.city||job.location||'Lieu non précisé'} · {remoteLabels[job.remote_type]}</p><div className="tags"><Tag>{job.contract_type}</Tag><Tag tone={job.is_demo?'amber':'lime'}>{job.is_demo?'Annonce fictive':'Offre collectée'}</Tag><Tag>{job.status}</Tag></div></div><div className="match-orb"><strong>{job.match.score??'—'}<small>{job.match.score!==null?'%':''}</small></strong><span>compatibilité</span></div></div>
 <div className="detail-actions">{!job.is_demo?<a className="btn primary" href={job.source_url} target="_blank" rel="noopener noreferrer">Voir l’offre originale <ArrowUpRight size={17}/></a>:<p className="notice">Démonstration : cette entreprise et cette offre sont fictives.</p>}<button className="btn" disabled={busy} onClick={save}>{saved?<Check size={16}/>:<Bookmark size={16}/>} {saved?'Enregistrée':'Enregistrer'}</button></div>
 <div className="detail-grid"><div><h3>La mission</h3><p className="job-description">{job.description||'Description non fournie par la source.'}</p><h3>Compétences identifiées</h3><div className="tags">{job.skills.length?job.skills.map((s:string)=><Tag key={s} tone={job.match.matched_skills.includes(s.toLowerCase())?'lime':''}>{s}</Tag>):<p>Non renseignées</p>}</div><p className="fine">Détectées dans le texte ; à vérifier dans l’annonce d’origine.</p><div className="source-info">Première détection : {dateLabel(job.first_seen)}<br/>Dernière observation : {dateLabel(job.last_seen)}<br/>Source : {job.source}</div></div><aside className="match-panel"><h3>Pourquoi ce score ?</h3><p className="fine">Un indice de proximité avec vos préférences, pas une probabilité d’embauche.</p>{job.match.breakdown.map((p:any)=><div className="match-row" key={p.label}><div><span>{p.label}</span><span>{Math.round(p.value*100)}%</span></div><div className="meter"><i style={{width:p.value*100+'%'}}/></div></div>)}{job.match.warnings.map((w:string)=><p className="fine" key={w}>ⓘ {w}</p>)}{job.match.missing_skills.length>0&&<><h4>À vérifier dans votre profil</h4><p className="fine">{job.match.missing_skills.join(', ')}</p></>}</aside></div>
 <section className="tailor-panel"><div><FileText size={22}/><h3>Un CV ciblé, fidèle à votre parcours.</h3></div><p>Mettre en avant les extraits pertinents, conserver le CV original et repérer les compétences absentes.</p>{resumes.length?<><label>CV à adapter<select value={resume} onChange={e=>setResume(e.target.value)}>{resumes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>{user.ai_available&&<label className="checkbox"><input type="checkbox" checked={useAI} onChange={e=>setAI(e.target.checked)}/>Utiliser l’IA : envoyer le texte du CV et de l’offre à OpenAI pour sélectionner les extraits.</label>}<button className="btn primary" disabled={busy||!resume} onClick={tailor}>{busy?'Traitement…':'Adapter mon CV'}<ArrowRight size={16}/></button></>:<a className="btn" href="#resumes" onClick={onClose}>Ajouter d’abord mon CV <ArrowRight size={16}/></a>}
 {result&&<div className="tailored-result"><Tag tone="lime">Version créée · {result.explanation.method}</Tag><p>{result.explanation.notice}</p><pre>{result.text}</pre>{result.explanation.missing_skills.length>0&&<p className="notice">Compétences non retrouvées dans votre CV : {result.explanation.missing_skills.join(', ')}. Elles n’ont pas été ajoutées.</p>}<a className="btn primary" href={'/api/tailored/'+result.id+'/download'}>Télécharger DOCX</a> <a className="btn" href={'/api/tailored/'+result.id+'/download?format=txt'}>Texte brut</a></div>}</section></> }</Modal>
}
export default function Jobs({user,onDetail,refresh}:{user:User;onDetail:(id:string)=>void;refresh:number}){
 const [stats,setStats]=useState<any>(null),[data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[q,setQ]=useState(''),[filters,setFilters]=useState({domain:'',contract:'',remote:'',demo:'all',sort:'match',city:''}),[page,setPage]=useState(1),[advanced,setAdvanced]=useState(false),[tick,setTick]=useState(0);
 useEffect(()=>{const t=setTimeout(()=>{setQ(search);setPage(1)},300);return()=>clearTimeout(t)},[search]);
 useEffect(()=>{let active=true;setLoading(true);setError('');Promise.all([api('/stats'),api('/jobs?'+new URLSearchParams({...filters,q,page:String(page),limit:'12'}))]).then(([s,d])=>{if(active){setStats(s);setData(d)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[q,filters,page,refresh,tick]);
 function filter(k:string,v:string){setFilters({...filters,[k]:v});setPage(1)}
 async function save(job:Job){try{await api('/saved/'+job.id,{method:job.saved_stage?'DELETE':'PUT',...(!job.saved_stage?{body:json({stage:'saved'})}:{})});setTick(t=>t+1)}catch(e:any){setError(e.message)}}
 return <><div className="page-heading"><div><div className="eyebrow"><span className="live-dot"/> VOTRE RADAR CARRIÈRE</div><h1>Le bon signal.<br/><span>Votre prochaine opportunité.</span></h1><p>Explorez les offres directement à la source. Trouvez celles qui vous ressemblent.</p></div><div className="radar-art" aria-hidden="true"><div className="radar-ring r1"/><div className="radar-ring r2"/><div className="radar-ring r3"/><div className="radar-cross"/><div className="radar-sweep"/><i className="blip b1"/><i className="blip b2"/><i className="blip b3"/><span>SCANNING OPPORTUNITIES</span></div></div>
 <div className="metrics"><div className="metric"><Radio/><div><strong>{stats?.real_jobs??'—'}</strong><span>offres réelles actives</span></div><Tag tone="lime">À la source</Tag></div><div className="metric"><Globe/><div><strong>{stats?.companies??'—'}</strong><span>entreprises référencées</span></div></div><div className="metric"><Bookmark/><div><strong>{stats?.saved??'—'}</strong><span>signaux enregistrés</span></div><a href="#saved" aria-label="Voir mes candidatures"><ArrowUpRight size={19}/></a></div></div>
 {!user.profile.skills?.length&&<div className="profile-banner"><div><strong>Donnez une direction à votre radar.</strong><span>Ajoutez vos compétences et vos préférences pour obtenir des scores utiles.</span></div><a href="#profile" className="btn">Configurer mon profil <ArrowRight size={16}/></a></div>}
 <div className="section-heading"><div><h2>Explorer les opportunités <span className="count">{data?.total??'—'}</span></h2><p>Les offres des entreprises, réunies au même endroit.</p></div><label className="sort">Trier par<select aria-label="Tri des offres" value={filters.sort} onChange={e=>filter('sort',e.target.value)}><option value="match">Compatibilité</option><option value="recent">Plus récentes</option></select></label></div>
 <div className="filter-bar"><label className="search-field"><Search size={19}/><input aria-label="Rechercher un métier, une compétence ou une entreprise" placeholder="Métier, compétence, entreprise…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Domaine" value={filters.domain} onChange={e=>filter('domain',e.target.value)}><option value="">Tous les domaines</option>{stats?.domains.map((d:string)=><option key={d}>{d}</option>)}</select><select aria-label="Type de contrat" value={filters.contract} onChange={e=>filter('contract',e.target.value)}><option value="">Tous les contrats</option>{['alternance','stage','CDI','CDD','graduate','freelance'].map(x=><option key={x}>{x}</option>)}</select><button className={'btn filter-toggle '+(advanced?'selected':'')} onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}><SlidersHorizontal size={17}/>Filtres</button></div>
 {advanced&&<div className="extra-filters"><label>Mode de travail<select value={filters.remote} onChange={e=>filter('remote',e.target.value)}><option value="">Tous les modes</option>{['remote','hybrid','onsite'].map(x=><option key={x} value={x}>{remoteLabels[x]}</option>)}</select></label><label>Ville<input value={filters.city} onChange={e=>filter('city',e.target.value)} placeholder="Paris, Marseille…"/></label><label>Origine des données<select value={filters.demo} onChange={e=>filter('demo',e.target.value)}><option value="all">Toutes</option><option value="real">Offres réelles uniquement</option><option value="demo">Démonstration uniquement</option></select></label><button className="text-btn" onClick={()=>{setSearch('');setFilters({domain:'',contract:'',remote:'',demo:'all',sort:'match',city:''});setPage(1)}}>Réinitialiser</button></div>}
 {stats?.demo_jobs>0&&filters.demo!=='real'&&<p className="demo-note"><span/>Environnement de démonstration : {stats.demo_jobs} offres fictives, identifiées sur chaque carte.</p>}
 {error&&<p className="error" role="alert">{error} <button className="text-btn" onClick={()=>setTick(t=>t+1)}>Réessayer</button></p>}
 {loading?<Loading/>:data?.items.length?<div className="jobs-grid">{data.items.map((j:Job)=><JobCard key={j.id} job={j} onOpen={()=>onDetail(j.id)} onSave={()=>save(j)}/>)}</div>:!error&&<Empty title="Aucun signal pour ces critères">Élargissez vos filtres. Un administrateur peut ajouter des entreprises et lancer leur collecte.</Empty>}
 {data&&data.ranked_total>12&&<div className="pagination"><button className="btn" disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/>Précédent</button><span>{page} / {Math.ceil(data.ranked_total/12)}</span><button className="btn" disabled={page*12>=data.ranked_total} onClick={()=>setPage(p=>p+1)}>Suivant<ChevronRight size={16}/></button></div>}
 {data?.total>data?.ranked_total&&<p className="fine">Compatibilité calculée sur les {data.ranked_total} offres les plus récentes. Affinez les filtres ou choisissez le tri chronologique.</p>}
 <footer className="page-footer"><span><span className="live-dot"/> DIRECT FROM THE SOURCE</span><span>SIGNAL / DISCOVER YOUR NEXT</span></footer></>
}
