import React,{useEffect,useState,Component,type ReactNode} from 'react';
import {createRoot} from 'react-dom/client';
import {Radar,Building2,Bookmark,FileText,UserRound,Settings2,LogOut,ArrowRight,ShieldCheck,ArrowUpRight,Menu,X,ChevronRight} from 'lucide-react';
import {api,json,setCsrf} from './api';
import {Logo,Loading} from './components';
import type {User} from './types';
import Jobs,{JobDetail} from './Jobs';
import Profile from './Profile';
import Resumes from './Resumes';
import Saved from './Saved';
import Companies from './Companies';
import './styles.css';
class Boundary extends Component<{children:ReactNode},{error:boolean}>{state={error:false};static getDerivedStateFromError(){return{error:true}}render(){return this.state.error?<main className="fatal"><h1>Le radar a rencontré une erreur.</h1><p>Vos données sont conservées. Rechargez pour reprendre.</p><button className="btn primary" onClick={()=>location.reload()}>Recharger</button></main>:this.props.children}}
function Auth({onLogin}:{onLogin:(u:User)=>void}){
 const [mode,setMode]=useState<'login'|'register'>('register'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const u=await api<User>('/auth/'+mode,{method:'POST',body:json({email,password,name:name||'Explorateur'})});setCsrf(u.csrf);onLogin(await api<User>('/auth/me'))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="auth-layout"><section className="auth-story"><Logo/><div className="auth-copy"><div className="eyebrow"><span className="live-dot"/> OPPORTUNITÉS À LA SOURCE</div><h1>La suite de votre<br/>parcours existe.<br/><span>Captez le signal.</span></h1><p>Au-delà des jobboards, les entreprises recrutent aussi chez elles. Retrouvez leurs offres, comprenez votre compatibilité et préparez votre candidature.</p><div className="auth-chips"><span>01 / DÉCOUVRIR</span><span>02 / MATCHER</span><span>03 / CANDIDATER</span></div></div><div className="auth-bottom"><ShieldCheck size={18}/>Vos CV restent privés. Vous gardez le contrôle.</div><div className="auth-orbit" aria-hidden="true"/></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><div className="eyebrow">BIENVENUE SUR SIGNAL</div><h2>{mode==='register'?'Votre radar vous attend.':'Bon retour sur le radar.'}</h2><p>{mode==='register'?'Créez votre espace et trouvez votre prochaine opportunité.':'Connectez-vous pour retrouver vos opportunités.'}</p><div className="auth-tabs"><button type="button" className={mode==='register'?'active':''} onClick={()=>{setMode('register');setError('')}}>Créer un compte</button><button type="button" className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>Se connecter</button></div>{mode==='register'&&<label>Votre prénom<input autoComplete="given-name" required value={name} maxLength={100} onChange={e=>setName(e.target.value)} placeholder="Comment vous appeler ?"/></label>}<label>Adresse email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="vous@exemple.fr"/></label><label>Mot de passe<input type="password" autoComplete={mode==='register'?'new-password':'current-password'} minLength={10} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="10 caractères minimum"/></label>{error&&<p className="error" role="alert">{error}</p>}<button className="btn primary full" disabled={busy}>{busy?'Connexion…':mode==='register'?'Activer mon radar':'Me connecter'}<ArrowRight size={18}/></button><p className="fine">Version locale · Démonstrations clairement identifiées.<br/>Aucune candidature n’est envoyée automatiquement.</p></form><div className="auth-version">SIGNAL / MVP 0.1 <span>DISCOVER YOUR NEXT ↗</span></div></section></div>
}
const nav=[{id:'jobs',label:'Mon radar',icon:Radar},{id:'companies',label:'Entreprises',icon:Building2},{id:'saved',label:'Mes candidatures',icon:Bookmark},{id:'resumes',label:'Studio CV',icon:FileText},{id:'profile',label:'Mon profil',icon:UserRound}];
function App(){
 const [user,setUser]=useState<User|null>(null),[initial,setInitial]=useState(true),[page,setPage]=useState(location.hash.slice(1)||'jobs'),[detail,setDetail]=useState<string|null>(null),[refresh,setRefresh]=useState(0),[menu,setMenu]=useState(false),[error,setError]=useState('');
 useEffect(()=>{api<User>('/auth/me').then(u=>{setCsrf(u.csrf);setUser(u)}).catch(()=>{}).finally(()=>setInitial(false));const onHash=()=>{setPage(location.hash.slice(1)||'jobs');setMenu(false);window.scrollTo(0,0)};window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);
 async function logout(){try{await api('/auth/logout',{method:'POST'});setUser(null);setCsrf('');setDetail(null)}catch(e:any){setError(e.message)}}
 if(initial)return <div className="boot"><Logo/><Loading/></div>;
 if(!user)return <Auth onLogin={setUser}/>;
 const active=[...nav,{id:'admin',label:'Collecte',icon:Settings2}].find(n=>n.id===page)?.label||'Mon radar';
 return <div className="app-shell"><a href="#main" className="skip-link" onClick={e=>{e.preventDefault();document.getElementById('main')?.focus()}}>Aller au contenu</a><aside className={'sidebar '+(menu?'open':'')}><a href="#jobs" aria-label="SIGNAL accueil"><Logo/></a><button className="mobile-close icon-btn" aria-label="Fermer la navigation" onClick={()=>setMenu(false)}><X/></button><div className="workspace"><span className="workspace-icon">S</span><div>Espace candidat<small>PERSONAL WORKSPACE</small></div><ChevronRight size={15}/></div><div className="nav-label">EXPLORER</div><nav>{nav.map(({id,label,icon:Icon})=><a key={id} href={'#'+id} className={page===id?'active':''}><Icon size={19}/>{label}{page===id&&<span className="nav-dot"/>}</a>)}{user.is_admin&&<><div className="nav-label admin-label">ADMINISTRATION</div><a href="#admin" className={page==='admin'?'active':''}><Settings2 size={19}/>Moteur de collecte</a></>}</nav><div className="sidebar-note"><span className="live-dot"/><strong>Le talent est partout.</strong><p>Les opportunités aussi.<br/>Allons les chercher.</p><ArrowUpRight size={19}/></div><div className="account"><div className="user-avatar">{user.name.slice(0,1).toUpperCase()}</div><div><strong>{user.name}</strong><small>{user.is_admin?'Administrateur':'Explorateur'}</small></div><button className="icon-btn" onClick={logout} aria-label="Se déconnecter"><LogOut size={17}/></button></div></aside>{menu&&<button className="nav-overlay" aria-label="Fermer le menu" onClick={()=>setMenu(false)}/>}
 <div className="main-shell"><header className="topbar"><button className="icon-btn mobile-menu" onClick={()=>setMenu(true)} aria-label="Ouvrir le menu"><Menu/></button><div className="breadcrumb">Workspace <ChevronRight size={13}/><strong>{active}</strong></div><div className="topbar-right"><span className="local-chip"><span className="live-dot"/>ESPACE LOCAL</span><a href="#profile" className="user-avatar" aria-label="Mon profil">{user.name[0].toUpperCase()}</a></div></header><main id="main" tabIndex={-1}>{error&&<p className="error">{error}</p>}{page==='profile'?<Profile user={user} onUpdate={setUser} onDeleted={()=>{setUser(null);setCsrf('')}}/>:page==='resumes'?<Resumes/>:page==='saved'?<Saved onDetail={setDetail} refresh={refresh}/>:page==='companies'||page==='admin'&&user.is_admin?<Companies key={page} user={user} adminView={page==='admin'}/>:<Jobs user={user} refresh={refresh} onDetail={setDetail}/>}</main></div>{detail&&<JobDetail id={detail} onClose={()=>setDetail(null)} user={user} onSaved={()=>setRefresh(r=>r+1)} onTailored={()=>setRefresh(r=>r+1)}/>}</div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><Boundary><App/></Boundary></React.StrictMode>);
