import {useState} from 'react';
import {Save,Download,Trash2,Check} from 'lucide-react';
import {api,json} from './api';
import {Modal} from './components';
import type {User} from './types';
const domains=['Software','Data','IA','Cybersecurity','DevOps','Automation','Finance','Marketing','Commerce','RH','Droit','Industrie','Santé','Ingénierie','Communication','Design','Autre'];
export default function Profile({user,onUpdate,onDeleted}:{user:User;onUpdate:(u:User)=>void;onDeleted:()=>void}){
 const [p,setP]=useState<Record<string,any>>({search_type:'Premier emploi',domains:[],skills:[],technologies:[],education_level:'',city:'',country:'France',radius_km:50,remote_types:[],contracts:[],languages:[],seniority:'junior',preferences:'',...user.profile}),[skillText,setSkills]=useState((user.profile.skills||[]).join(', ')),[techText,setTech]=useState((user.profile.technologies||[]).join(', ')),[langText,setLang]=useState((user.profile.languages||[]).join(', ')),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false),[confirm,setConfirm]=useState(false);
 function field(k:string,v:any){setP({...p,[k]:v});setSuccess(false)}
 function toggle(k:string,v:string){field(k,p[k].includes(v)?p[k].filter((s:string)=>s!==v):[...p[k],v])}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const profile={...p,skills:skillText.split(',').map((s:string)=>s.trim()).filter(Boolean),technologies:techText.split(',').map((s:string)=>s.trim()).filter(Boolean),languages:langText.split(',').map((s:string)=>s.trim()).filter(Boolean)};const u=await api('/profile',{method:'PUT',body:json(profile)});onUpdate({...user,...u});setSuccess(true)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function remove(){setBusy(true);try{await api('/account',{method:'DELETE'});onDeleted()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function download(){try{const data=await api('/account/export');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='signal-mes-donnees.json';a.click();URL.revokeObjectURL(url)}catch(e:any){setError(e.message)}}
 return <><div className="simple-heading"><div className="eyebrow">CALIBRER LE RADAR</div><h1>Votre profil. Vos critères.</h1><p>Un matching transparent commence par des préférences précises.</p></div><form onSubmit={save} className="profile-layout"><div className="panel"><h2>01 / Votre recherche</h2><div className="form-grid"><label>Objectif<select value={p.search_type} onChange={e=>field('search_type',e.target.value)}>{['Premier emploi','Stage ou alternance','Évolution professionnelle','Reconversion','Mission freelance'].map(x=><option key={x}>{x}</option>)}</select></label><label>Niveau d’expérience<select value={p.seniority} onChange={e=>field('seniority',e.target.value)}><option value="junior">Junior</option><option value="mid">Intermédiaire</option><option value="senior">Senior</option><option value="">Sans préférence</option></select></label><label>Niveau d’études<input value={p.education_level} onChange={e=>field('education_level',e.target.value)} placeholder="Bac +3, master, BTS…"/></label><label>Pays<input value={p.country} onChange={e=>field('country',e.target.value)}/></label></div><h3>Contrats recherchés</h3><div className="choice-list">{['alternance','stage','CDI','CDD','intérim','graduate','freelance'].map(x=><button type="button" key={x} aria-pressed={p.contracts.includes(x)} className={p.contracts.includes(x)?'choice active':'choice'} onClick={()=>toggle('contracts',x)}>{x}</button>)}</div><h3>Domaines d’activité</h3><div className="choice-list">{domains.map(x=><button type="button" key={x} aria-pressed={p.domains.includes(x)} className={p.domains.includes(x)?'choice active':'choice'} onClick={()=>toggle('domains',x)}>{x}</button>)}</div></div>
 <div className="panel"><h2>02 / Vos compétences</h2><label>Compétences · séparées par des virgules<textarea rows={3} value={skillText} onChange={e=>setSkills(e.target.value)} placeholder="Python, SQL, gestion de projet…"/></label><label>Technologies<textarea rows={2} value={techText} onChange={e=>setTech(e.target.value)} placeholder="Docker, AWS, React…"/></label><label>Langues<input value={langText} onChange={e=>setLang(e.target.value)} placeholder="Français, anglais…"/></label><p className="fine">Les compétences et technologies alimentent le score. Études, langues et préférences sont enregistrées pour consultation ; elles ne sont pas encore pondérées.</p></div>
 <div className="panel"><h2>03 / Votre terrain de jeu</h2><div className="form-grid"><label>Ville<input value={p.city} onChange={e=>field('city',e.target.value)} placeholder="Marseille"/></label><label>Rayon en kilomètres<input type="number" min="1" max="20000" value={p.radius_km} onChange={e=>field('radius_km',Number(e.target.value))}/></label><label>Latitude (facultatif)<input type="number" step="any" min="-90" max="90" value={p.latitude??''} onChange={e=>field('latitude',e.target.value===''?null:Number(e.target.value))} placeholder="43.2965"/></label><label>Longitude (facultatif)<input type="number" step="any" min="-180" max="180" value={p.longitude??''} onChange={e=>field('longitude',e.target.value===''?null:Number(e.target.value))} placeholder="5.3698"/></label></div><p className="fine">Le rayon est calculé quand votre profil et l’offre possèdent des coordonnées. Sinon, le score compare les villes.</p><div className="choice-list">{[['remote','Télétravail'],['hybrid','Hybride'],['onsite','Sur site']].map(([v,l])=><button type="button" key={v} className={p.remote_types.includes(v)?'choice active':'choice'} aria-pressed={p.remote_types.includes(v)} onClick={()=>toggle('remote_types',v)}>{l}</button>)}</div><label>Autres préférences<textarea value={p.preferences} onChange={e=>field('preferences',e.target.value)} maxLength={2000} placeholder="Ce qui compte pour vous…"/></label></div>
 <div className="profile-save">{error&&<p className="error" role="alert">{error}</p>}{success&&<p className="success"><Check size={17}/>Profil enregistré. Votre radar est à jour.</p>}<button className="btn primary" disabled={busy}><Save size={17}/>{busy?'Enregistrement…':'Enregistrer mon profil'}</button></div></form>
 <section className="panel privacy-panel"><div><h2>Vos données vous appartiennent.</h2><p>CV et profil privés. Exportez vos données ou supprimez votre compte et ses documents.</p></div><div className="actions"><button className="btn" onClick={download}><Download size={16}/>Exporter</button><button className="btn danger" onClick={()=>setConfirm(true)}><Trash2 size={16}/>Supprimer mon compte</button></div></section>{confirm&&<Modal title="Supprimer votre compte ?" onClose={()=>setConfirm(false)}><p>Cette action efface votre profil, vos CV, leurs versions adaptées, vos favoris et vos sessions. Elle est définitive.</p><div className="actions"><button className="btn" onClick={()=>setConfirm(false)}>Annuler</button><button className="btn danger" disabled={busy} onClick={remove}>Confirmer la suppression</button></div></Modal>}</>
}
