import {useEffect,useState,useRef} from 'react';
import {Upload,Plus,FileText,Trash2,Download,ArrowRight} from 'lucide-react';
import {api,json} from './api';
import {Tag,Empty,Loading,Modal,dateLabel} from './components';
import type {Resume} from './types';
export default function Resumes(){
 const [resumes,setResumes]=useState<Resume[]>([]),[versions,setVersions]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[add,setAdd]=useState(false),[name,setName]=useState('Mon CV'),[text,setText]=useState(''),[view,setView]=useState<Resume|null>(null),[remove,setRemove]=useState<Resume|null>(null);const file=useRef<HTMLInputElement>(null);
 async function load(){try{const [r,v]=await Promise.all([api<Resume[]>('/resumes'),api<any[]>('/tailored')]);setResumes(r);setVersions(v)}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function upload(f:File){setError('');if(f.size>5*1024*1024){setError('Fichier limité à 5 Mo');return}setBusy(true);try{const form=new FormData();form.append('file',f);await api('/resumes/upload',{method:'POST',body:form});await load()}catch(e:any){setError(e.message)}finally{setBusy(false);if(file.current)file.current.value=''}}
 async function create(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('/resumes',{method:'POST',body:json({name,text})});setAdd(false);setText('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function del(){if(!remove)return;setBusy(true);try{await api('/resumes/'+remove.id,{method:'DELETE'});setRemove(null);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><div className="simple-heading"><div className="eyebrow">CANDIDATURE STUDIO</div><h1>Votre parcours, bien présenté.</h1><p>Importez votre CV, puis adaptez-le à une offre depuis le radar.</p></div>{error&&<p className="error" role="alert">{error}</p>}<div className="upload-zone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(!busy&&e.dataTransfer.files[0])upload(e.dataTransfer.files[0])}}><span className="upload-icon"><Upload size={27}/></span><h2>{busy?'Traitement du document…':'Votre prochain chapitre commence ici.'}</h2><p>Glissez votre CV ou choisissez un fichier. PDF texte, DOCX ou TXT · 5 Mo max.</p><div className="actions"><button className="btn primary" onClick={()=>file.current?.click()} disabled={busy}><Upload size={16}/>Importer mon CV</button><button className="btn" onClick={()=>setAdd(true)} disabled={busy}><Plus size={16}/>Coller le texte</button></div><input ref={file} type="file" accept=".pdf,.docx,.txt" className="visually-hidden" aria-label="Importer un CV" onChange={e=>{if(e.target.files?.[0])upload(e.target.files[0])}}/><p className="fine">Privé par défaut. Aucun envoi à un service IA sans sélection explicite de cette option.</p></div>
 <div className="section-heading"><h2>Mes CV <span className="count">{resumes.length}</span></h2><a className="text-btn" href="#jobs">Trouver une offre <ArrowRight size={16}/></a></div>{loading?<Loading/>:resumes.length?<div className="resume-grid">{resumes.map(r=><article key={r.id} className="panel resume-card"><FileText className="accent" size={30}/><div><h3>{r.name}</h3><p>{dateLabel(r.created_at)} · {r.text.length.toLocaleString('fr-FR')} caractères</p></div><div className="actions"><button className="btn" onClick={()=>setView(r)}>Lire le texte extrait</button><button className="icon-btn" aria-label={'Supprimer '+r.name} onClick={()=>setRemove(r)}><Trash2 size={17}/></button></div></article>)}</div>:<Empty title="Votre studio est prêt">Ajoutez votre premier CV pour créer une candidature ciblée.</Empty>}
 <div className="section-heading"><h2>Versions adaptées <span className="count">{versions.length}</span></h2></div>{versions.length?<div className="versions">{versions.map(v=><article className="panel version" key={v.id}><div><Tag tone="lime">{v.explanation.method==='ai-extractive'?'Sélection IA':'Sélection locale'}</Tag><h3>{v.text.split('\n')[0]}</h3><small>{dateLabel(v.created_at)}</small><p className="fine">{v.explanation.notice}</p></div><div className="actions"><button className="btn" onClick={()=>setView({...v,name:'CV adapté'})}>Relire</button><a href={'/api/tailored/'+v.id+'/download'} className="btn primary"><Download size={16}/>DOCX</a></div></article>)}</div>:<p className="fine">Ouvrez une offre et cliquez sur « Adapter mon CV ». Les versions apparaîtront ici.</p>}
 {add&&<Modal title="Ajouter un CV texte" onClose={()=>setAdd(false)}><form onSubmit={create}><label>Nom du document<input required value={name} onChange={e=>setName(e.target.value)} maxLength={200}/></label><label>Votre parcours<textarea required minLength={40} maxLength={50000} rows={13} value={text} onChange={e=>setText(e.target.value)} placeholder="Coordonnées, expériences, formation, compétences…"/></label><p className="fine">Minimum 40 caractères. Conservez les dates et les intitulés exacts.</p>{error&&<p className="error">{error}</p>}<button className="btn primary" disabled={busy}>Enregistrer le CV</button></form></Modal>}{view&&<Modal wide title={view.name} onClose={()=>setView(null)}><pre className="resume-text">{view.text}</pre></Modal>}{remove&&<Modal title="Supprimer ce CV ?" onClose={()=>setRemove(null)}><p>Le document « {remove.name} » et toutes ses versions adaptées seront supprimés.</p><button className="btn danger" disabled={busy} onClick={del}>Supprimer le document</button></Modal>}</>
}
