import {useEffect,useState} from 'react';
import {ArrowUpRight,Trash2} from 'lucide-react';
import {api,json} from './api';
import {Empty,Loading,Tag,stageLabels,Modal} from './components';
export default function Saved({onDetail,refresh}:{onDetail:(id:string)=>void;refresh:number}){
 const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[edit,setEdit]=useState<any>(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{setRows(await api('/saved'))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[refresh]);
 async function update(row:any,stage:string,newNote=row.note){setBusy(true);try{await api('/saved/'+row.job_id,{method:'PUT',body:json({stage,note:newNote})});await load();setEdit(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function remove(id:string){try{await api('/saved/'+id,{method:'DELETE'});await load()}catch(e:any){setError(e.message)}}
 return <><div className="simple-heading"><div className="eyebrow">VOTRE TRAJECTOIRE</div><h1>Chaque candidature compte.</h1><p>Gardez vos opportunités en vue, de la découverte à la proposition.</p></div>{error&&<p role="alert" className="error">{error}</p>}<div className="pipeline-stats">{Object.entries(stageLabels).map(([k,v])=><div key={k}><strong>{rows.filter(r=>r.stage===k).length}</strong><span>{v}</span></div>)}</div>{loading?<Loading/>:!rows.length?<Empty title="Votre prochaine étape est sur le radar">Enregistrez une offre pour la retrouver et suivre votre candidature ici.</Empty>:<div className="saved-list">{rows.map(row=><article className="panel saved-row" key={row.id}><div className="saved-info"><small>{row.company}</small><button className="job-title" onClick={()=>onDetail(row.job_id)}>{row.job.title}<ArrowUpRight size={17}/></button><div className="tags"><Tag>{row.job.contract_type}</Tag><Tag tone={row.job.is_demo?'amber':'lime'}>{row.job.is_demo?'Démo':row.job.status}</Tag></div>{row.note&&<p className="saved-note">{row.note}</p>}</div><div className="saved-actions"><select aria-label={'Statut de '+row.job.title} disabled={busy} value={row.stage} onChange={e=>update(row,e.target.value)}>{Object.entries(stageLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><div className="actions"><button className="text-btn" onClick={()=>{setEdit(row);setNote(row.note)}}>Modifier la note</button><button className="icon-btn" aria-label="Retirer du suivi" onClick={()=>remove(row.job_id)}><Trash2 size={17}/></button></div></div></article>)}</div>}{edit&&<Modal title="Note de candidature" onClose={()=>setEdit(null)}><p>{edit.job.title}</p><textarea aria-label="Votre note" rows={6} maxLength={3000} value={note} onChange={e=>setNote(e.target.value)}/><p className="fine">Note privée, visible uniquement par vous.</p><button className="btn primary" disabled={busy} onClick={()=>update(edit,edit.stage,note)}>Enregistrer</button></Modal>}</>
}
